language: ruby
rvm:
  - 2.5.0
  - 2.6.0
  - 2.7.0
install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'
script:
  - bundle install
  - bundle exec rspec spec
  - bundle exec rubocop
